### ISSUE TITLE
addFDS a addFSS

### ISSUE THREAD

**Issue by jakubmilata** [MikyWoW/gls_api#3]
Bylo by prosím možné implementovat tyto funkce? 

	/**
	* Flexible Delivery Service !NOT IMPLEMENTED!
	*/
	public function addFDS($Value)
	{
		throw new \Exception("Not implemented exception.");
	}

	/**
	* Flexible delivery Sms Service !NOT IMPLEMENTED!
	*/
	public function addFSS($Value)
	{
		throw new \Exception("Not implemented exception.");
	}

Bez mailů a SMSek máme nižší doručitelnost balíků. Za implementaci rád zaplatím.

**Comment by MikyWoW** [comment]
Myslel jsem že email je standard a chodí vždy pokud je vyplněn v kontaktní osobě. A SMS že je za příplatek "SMS Service" addSM1($value) která ale také není implementována. Nějak se v těch jejich službách nevyznám.

To co požadujete je flexibilní doručení: https://gls-group.com/CZ/cs/prepravni-reseni/sluzby/flexdeliveryservice

Implementace všech tří funkcí je jednoduchá. Můžete klidně poslat PR (pull request) pokud to zvládnete implementovat sám. Osobně to vidím možná na konci příštího týdne.

**Comment by jakubmilata** [comment]
SMS je za příplatek, pokud chceme sms, je to třeba nějak odeslat přes api. 
A ty maily jsou sice zdarma, ale pokud vím taky nechodí pokud se to v api nějak nenastaví. 
Raději bych vám zaplatil za implementaci. Já to bohužel nezvládnu.

**Comment by MikyWoW** [comment]
Vyřešeno verze 1.0.4

**Comment by jakubmilata** [comment]
Dobrý den,

díky moc za vyřešení. Potvrzuji, že nám to funguje. Můžete mi poslat
fakturu na ***@***.*** IČ: 27790690

s pozdravem
Jakub Milata

>
